version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  migration_script:
    build:
      context: .
    container_name: migration_container
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/
    volumes:
      - ./healthcare_dataset.csv:/app/healthcare_dataset.csv
    command: ["python", "migrate_to_mongodb.py"]

volumes:
  mongo_data:
